/**
 * A shared bilingual vocabulary for reading identifiers as business language.
 *
 * This is deliberately **generic software and business vocabulary**, never a
 * per-project dictionary: `create`, `order`, `draft`, and `retry` mean the same
 * thing in every repository, so translating them is reading, not guessing. A term
 * that only makes sense in one product does not belong here — that is what the
 * documented-capability match and the config override are for.
 *
 * The rule that keeps this honest: a token this vocabulary does not know is
 * **kept verbatim and reported**, never invented. A name nothing resolves is
 * marked pending rather than dressed up as understood.
 */

export interface Term {
  zhCN: string;
  /** The English business reading; defaults to the capitalized token. */
  enUS?: string;
}

/** Verbs: what a step does. */
const VERBS: Record<string, Term> = {
  add: { zhCN: "添加" },
  aggregate: { zhCN: "汇总" },
  analyze: { zhCN: "分析" },
  append: { zhCN: "追加" },
  apply: { zhCN: "应用" },
  approve: { zhCN: "批准" },
  archive: { zhCN: "归档" },
  assess: { zhCN: "评估" },
  assign: { zhCN: "分配" },
  attach: { zhCN: "附加" },
  authorize: { zhCN: "授权" },
  build: { zhCN: "组装" },
  calculate: { zhCN: "计算" },
  cancel: { zhCN: "取消" },
  capture: { zhCN: "采集" },
  charge: { zhCN: "扣款" },
  check: { zhCN: "检查" },
  classify: { zhCN: "分类" },
  clean: { zhCN: "清理" },
  collect: { zhCN: "收集" },
  compile: { zhCN: "编译" },
  compose: { zhCN: "编排" },
  compute: { zhCN: "计算" },
  confirm: { zhCN: "确认" },
  convert: { zhCN: "转换" },
  create: { zhCN: "创建" },
  delete: { zhCN: "删除" },
  deliver: { zhCN: "投递" },
  detect: { zhCN: "检测" },
  dispatch: { zhCN: "派发" },
  download: { zhCN: "下载" },
  draft: { zhCN: "起草" },
  enqueue: { zhCN: "入队" },
  enrich: { zhCN: "补全" },
  evaluate: { zhCN: "评估" },
  execute: { zhCN: "执行" },
  export: { zhCN: "导出" },
  extract: { zhCN: "提取" },
  fetch: { zhCN: "获取" },
  filter: { zhCN: "筛选" },
  finalize: { zhCN: "定稿" },
  find: { zhCN: "查找" },
  generate: { zhCN: "生成" },
  get: { zhCN: "读取" },
  grade: { zhCN: "评级" },
  handle: { zhCN: "处理" },
  import: { zhCN: "导入" },
  index: { zhCN: "索引" },
  ingest: { zhCN: "接入" },
  initialize: { zhCN: "初始化" },
  invoke: { zhCN: "调用" },
  list: { zhCN: "列出" },
  load: { zhCN: "加载" },
  lock: { zhCN: "锁定" },
  match: { zhCN: "匹配" },
  merge: { zhCN: "合并" },
  moderate: { zhCN: "审核" },
  notify: { zhCN: "通知" },
  parse: { zhCN: "解析" },
  persist: { zhCN: "持久化" },
  plan: { zhCN: "规划" },
  poll: { zhCN: "轮询" },
  prepare: { zhCN: "准备" },
  process: { zhCN: "处理" },
  publish: { zhCN: "发布" },
  purge: { zhCN: "清除" },
  query: { zhCN: "查询" },
  queue: { zhCN: "排队" },
  rank: { zhCN: "排序" },
  read: { zhCN: "读取" },
  rebuild: { zhCN: "重建" },
  receive: { zhCN: "接收" },
  record: { zhCN: "记录" },
  refresh: { zhCN: "刷新" },
  refund: { zhCN: "退款" },
  register: { zhCN: "注册" },
  reject: { zhCN: "拒绝" },
  release: { zhCN: "发布" },
  remove: { zhCN: "移除" },
  render: { zhCN: "渲染" },
  resolve: { zhCN: "解析" },
  retrieve: { zhCN: "检索" },
  retry: { zhCN: "重试" },
  review: { zhCN: "审核" },
  revise: { zhCN: "修改" },
  run: { zhCN: "运行" },
  save: { zhCN: "保存" },
  schedule: { zhCN: "调度" },
  score: { zhCN: "评分" },
  search: { zhCN: "搜索" },
  select: { zhCN: "选择" },
  send: { zhCN: "发送" },
  ship: { zhCN: "发货" },
  split: { zhCN: "拆分" },
  store: { zhCN: "存储" },
  stream: { zhCN: "传输" },
  submit: { zhCN: "提交" },
  summarize: { zhCN: "总结" },
  sync: { zhCN: "同步" },
  track: { zhCN: "跟踪" },
  transcribe: { zhCN: "转写" },
  transform: { zhCN: "转换" },
  translate: { zhCN: "翻译" },
  trigger: { zhCN: "触发" },
  update: { zhCN: "更新" },
  upload: { zhCN: "上传" },
  upsert: { zhCN: "写入" },
  validate: { zhCN: "校验" },
  verify: { zhCN: "验证" },
  write: { zhCN: "写入" },
  lookup: { zhCN: "查询" },
  probe: { zhCN: "探测" },
  reconcile: { zhCN: "对账" },
  seed: { zhCN: "初始化" },
  serve: { zhCN: "服务" },
  sign: { zhCN: "签名" },
  start: { zhCN: "启动" },
  stop: { zhCN: "停止" },
  subscribe: { zhCN: "订阅" },
  tag: { zhCN: "打标" },
  test: { zhCN: "测试" },
  toggle: { zhCN: "切换" },
  unlock: { zhCN: "解锁" },
  watch: { zhCN: "监听" },
};

/** Nouns: what a step acts on. */
const NOUNS: Record<string, Term> = {
  account: { zhCN: "账户" },
  action: { zhCN: "动作" },
  agent: { zhCN: "智能体" },
  answer: { zhCN: "回答" },
  api: { zhCN: "接口", enUS: "API" },
  approval: { zhCN: "审批" },
  article: { zhCN: "文章" },
  asset: { zhCN: "素材" },
  attempt: { zhCN: "尝试" },
  audio: { zhCN: "音频" },
  batch: { zhCN: "批次" },
  billing: { zhCN: "计费" },
  body: { zhCN: "请求体" },
  cache: { zhCN: "缓存" },
  campaign: { zhCN: "活动" },
  cart: { zhCN: "购物车" },
  category: { zhCN: "分类" },
  chat: { zhCN: "对话" },
  checkout: { zhCN: "结算" },
  chunk: { zhCN: "分块" },
  claim: { zhCN: "申诉" },
  comment: { zhCN: "评论" },
  config: { zhCN: "配置" },
  content: { zhCN: "内容" },
  context: { zhCN: "上下文" },
  conversation: { zhCN: "会话" },
  customer: { zhCN: "客户" },
  data: { zhCN: "数据" },
  database: { zhCN: "数据库" },
  decision: { zhCN: "决策" },
  detail: { zhCN: "详情" },
  digest: { zhCN: "摘要" },
  director: { zhCN: "导演" },
  document: { zhCN: "文档" },
  draft: { zhCN: "草稿" },
  email: { zhCN: "邮件" },
  embedding: { zhCN: "向量" },
  entry: { zhCN: "条目" },
  error: { zhCN: "错误" },
  event: { zhCN: "事件" },
  evidence: { zhCN: "证据" },
  feedback: { zhCN: "反馈" },
  file: { zhCN: "文件" },
  frame: { zhCN: "分镜" },
  gate: { zhCN: "关卡" },
  idea: { zhCN: "创意" },
  image: { zhCN: "图片" },
  input: { zhCN: "输入" },
  instruction: { zhCN: "指令" },
  intent: { zhCN: "意图" },
  invoice: { zhCN: "账单" },
  item: { zhCN: "条目" },
  job: { zhCN: "作业" },
  knowledge: { zhCN: "知识" },
  label: { zhCN: "标签" },
  language: { zhCN: "语言" },
  layout: { zhCN: "布局" },
  lead: { zhCN: "线索" },
  library: { zhCN: "素材库" },
  log: { zhCN: "日志" },
  message: { zhCN: "消息" },
  meta: { zhCN: "元信息" },
  metric: { zhCN: "指标" },
  model: { zhCN: "模型" },
  notification: { zhCN: "通知" },
  order: { zhCN: "订单" },
  output: { zhCN: "输出" },
  page: { zhCN: "页面" },
  payment: { zhCN: "支付" },
  permission: { zhCN: "权限" },
  photo: { zhCN: "照片" },
  pipeline: { zhCN: "流水线" },
  plan: { zhCN: "计划" },
  policy: { zhCN: "策略" },
  post: { zhCN: "帖子" },
  price: { zhCN: "价格" },
  product: { zhCN: "商品" },
  profile: { zhCN: "档案" },
  project: { zhCN: "项目" },
  prompt: { zhCN: "提示词" },
  provider: { zhCN: "供应商" },
  quality: { zhCN: "质量" },
  query: { zhCN: "查询" },
  question: { zhCN: "问题" },
  quote: { zhCN: "报价" },
  rating: { zhCN: "评分" },
  record: { zhCN: "记录" },
  refund: { zhCN: "退款" },
  reply: { zhCN: "回复" },
  report: { zhCN: "报告" },
  request: { zhCN: "请求" },
  response: { zhCN: "响应" },
  result: { zhCN: "结果" },
  review: { zhCN: "审核" },
  role: { zhCN: "角色" },
  route: { zhCN: "路由" },
  rule: { zhCN: "规则" },
  scene: { zhCN: "场景" },
  schedule: { zhCN: "排期" },
  scope: { zhCN: "范围" },
  script: { zhCN: "剧本" },
  search: { zhCN: "搜索" },
  section: { zhCN: "章节" },
  session: { zhCN: "会话" },
  setting: { zhCN: "设置" },
  shipment: { zhCN: "物流" },
  source: { zhCN: "来源" },
  state: { zhCN: "状态" },
  status: { zhCN: "状态" },
  step: { zhCN: "步骤" },
  story: { zhCN: "故事" },
  stream: { zhCN: "流" },
  subscription: { zhCN: "订阅" },
  summary: { zhCN: "摘要" },
  task: { zhCN: "任务" },
  template: { zhCN: "模板" },
  text: { zhCN: "文本" },
  thread: { zhCN: "话题" },
  ticket: { zhCN: "工单" },
  token: { zhCN: "令牌" },
  tool: { zhCN: "工具" },
  topic: { zhCN: "主题" },
  transcript: { zhCN: "文字记录" },
  usage: { zhCN: "用量" },
  user: { zhCN: "用户" },
  version: { zhCN: "版本" },
  video: { zhCN: "视频" },
  voice: { zhCN: "语音" },
  webhook: { zhCN: "回调" },
  workflow: { zhCN: "工作流" },
  workspace: { zhCN: "工作区" },
  attachment: { zhCN: "附件" },
  author: { zhCN: "作者" },
  balance: { zhCN: "余额" },
  brief: { zhCN: "需求说明" },
  budget: { zhCN: "预算" },
  channel: { zhCN: "渠道" },
  client: { zhCN: "客户端" },
  cost: { zhCN: "成本" },
  editor: { zhCN: "编辑器" },
  form: { zhCN: "表单" },
  header: { zhCN: "请求头" },
  history: { zhCN: "历史" },
  key: { zhCN: "密钥" },
  ledger: { zhCN: "台账" },
  limit: { zhCN: "上限" },
  link: { zhCN: "链接" },
  member: { zhCN: "成员" },
  owner: { zhCN: "负责人" },
  parameter: { zhCN: "参数" },
  reader: { zhCN: "读取器" },
  reviewer: { zhCN: "审核人" },
  schema: { zhCN: "结构" },
  score: { zhCN: "评分" },
  segment: { zhCN: "片段" },
  server: { zhCN: "服务端" },
  shot: { zhCN: "镜头" },
  slot: { zhCN: "档位" },
  snapshot: { zhCN: "快照" },
  storyboard: { zhCN: "分镜脚本" },
  subtitle: { zhCN: "字幕" },
  team: { zhCN: "团队" },
  thumbnail: { zhCN: "缩略图" },
  title: { zhCN: "标题" },
  track: { zhCN: "轨道" },
  writer: { zhCN: "撰写器" },
};

/** Qualifiers: which one, or in what manner. */
const QUALIFIERS: Record<string, Term> = {
  active: { zhCN: "生效" },
  all: { zhCN: "全部" },
  auto: { zhCN: "自动" },
  bulk: { zhCN: "批量" },
  current: { zhCN: "当前" },
  daily: { zhCN: "每日" },
  default: { zhCN: "默认" },
  draft: { zhCN: "草稿" },
  external: { zhCN: "外部" },
  fallback: { zhCN: "兜底" },
  fast: { zhCN: "快速" },
  final: { zhCN: "最终" },
  full: { zhCN: "完整" },
  human: { zhCN: "人工" },
  initial: { zhCN: "初始" },
  internal: { zhCN: "内部" },
  latest: { zhCN: "最新" },
  local: { zhCN: "本地" },
  manual: { zhCN: "手动" },
  new: { zhCN: "新" },
  next: { zhCN: "下一个" },
  pending: { zhCN: "待处理" },
  primary: { zhCN: "主要" },
  private: { zhCN: "私有" },
  public: { zhCN: "公开" },
  raw: { zhCN: "原始" },
  remote: { zhCN: "远程" },
  shared: { zhCN: "共享" },
  single: { zhCN: "单个" },
  static: { zhCN: "静态" },
  total: { zhCN: "总计" },
};

export const VOCABULARY: Record<string, Term> = { ...NOUNS, ...QUALIFIERS, ...VERBS };

/**
 * Words that describe an implementation shape rather than a business meaning.
 * Dropping them is what turns `handleTicketController` into 处理工单 instead of
 * 处理工单控制器 — the reader is looking at a step, not at its class name.
 */
export const STRUCTURAL_TOKENS = new Set([
  "controller", "handler", "impl", "middleware", "provider", "repository",
  "service", "usecase", "util", "utils", "helper", "helpers", "wrapper",
]);

/** Plural and tense forms resolve to the same term as their stem. */
export function normalizeToken(token: string): string {
  const lower = token.toLowerCase();
  if (VOCABULARY[lower]) return lower;
  for (const [suffix, replacement] of [["ies", "y"], ["ses", "s"], ["es", ""], ["s", ""], ["ing", ""], ["ed", ""]] as const) {
    if (lower.length > suffix.length + 2 && lower.endsWith(suffix)) {
      const stem = lower.slice(0, -suffix.length) + replacement;
      if (VOCABULARY[stem]) return stem;
      // `applying` -> `apply`: a dropped `e` comes back with the `y`.
      if (suffix === "ing" && VOCABULARY[`${stem}e`]) return `${stem}e`;
    }
  }
  return lower;
}

/** Splits an identifier into its words: camelCase, snake_case, kebab-case. */
export function tokenizeIdentifier(value: string): string[] {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1 $2")
    .replace(/[-_./]+/g, " ")
    .trim()
    .split(/\s+/)
    .filter(Boolean);
}
