import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

/**
 * `init --github`: the one-time setup after which GitHub keeps the map current.
 * The generated workflow references the `@v1` action, so compatible analyzer
 * updates arrive without the user editing anything — including via the weekly
 * schedule, which re-maps the repository even when nobody has pushed.
 *
 * The file carries an integrity line so a later `init --github` can tell the
 * difference between "our file, possibly from an older template" (safe to update)
 * and "the user edited this" (never silently overwritten).
 */

const INTEGRITY_PREFIX = "# agent-runtime-map-integrity: ";

export const GITHUB_WORKFLOW_RELATIVE_PATH = ".github/workflows/agent-runtime-map.yml";

/**
 * The template deliberately grants nothing beyond `contents: read`, cancels
 * superseded runs per ref, and never commits to the user's branch — the map is an
 * artifact and a step summary, not a push, so no run can trigger another.
 */
export function githubWorkflowTemplate(): string {
  const body = `# Generated by \`agent-runtime-map init --github\`.
# Re-running init updates this file only while it is unmodified; edits are yours to keep.
name: Agent Runtime Map

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  schedule:
    # Weekly, so a compatible analyzer update re-maps the repository even
    # without a push. Remove this block if you only want push/PR builds.
    - cron: "17 6 * * 1"

permissions:
  contents: read

concurrency:
  group: agent-runtime-map-\${{ github.ref }}
  cancel-in-progress: true

jobs:
  map:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tangyishun9846/agent-runtime-map@v1
`;
  return `${INTEGRITY_PREFIX}${integrityOf(body)}\n${body}`;
}

function integrityOf(body: string): string {
  return createHash("sha256").update(body).digest("hex").slice(0, 16);
}

/**
 * Whether existing workflow content is an unmodified product of this generator —
 * any version of it. The hash covers everything below the integrity line, so a
 * single edited character makes the file the user's.
 */
export function isGeneratedWorkflow(content: string): boolean {
  const newline = content.indexOf("\n");
  if (newline < 0 || !content.startsWith(INTEGRITY_PREFIX)) return false;
  const declared = content.slice(INTEGRITY_PREFIX.length, newline).trim();
  return declared === integrityOf(content.slice(newline + 1));
}

export type GithubWorkflowOutcome = "created" | "updated" | "overwritten" | "unchanged";

export class WorkflowModifiedError extends Error {
  constructor(public readonly workflowFile: string) {
    super(`${workflowFile} exists and has local modifications; it was not touched. Re-run with --force to overwrite it.`);
    this.name = "WorkflowModifiedError";
  }
}

export async function initGithubWorkflow(
  root: string,
  options: { force?: boolean } = {},
): Promise<{ workflowFile: string; outcome: GithubWorkflowOutcome }> {
  const workflowFile = path.join(path.resolve(root), GITHUB_WORKFLOW_RELATIVE_PATH);
  const next = githubWorkflowTemplate();

  let existing: string | undefined;
  try {
    existing = await readFile(workflowFile, "utf8");
  } catch {
    existing = undefined;
  }

  if (existing !== undefined) {
    if (existing === next) return { workflowFile, outcome: "unchanged" };
    const generated = isGeneratedWorkflow(existing);
    if (!generated && !options.force) throw new WorkflowModifiedError(workflowFile);
    await writeFile(workflowFile, next, "utf8");
    // "updated" is routine template refresh; "overwritten" says user work was
    // discarded — the caller should word those differently.
    return { workflowFile, outcome: generated ? "updated" : "overwritten" };
  }

  await mkdir(path.dirname(workflowFile), { recursive: true });
  await writeFile(workflowFile, next, "utf8");
  return { workflowFile, outcome: "created" };
}
