import { execFile } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);

/**
 * `init --github`: the one-time setup after which GitHub keeps the map current.
 * The generated workflow references the `@v1` action, so compatible analyzer
 * updates arrive without the user editing anything — including via the weekly
 * schedule, which re-maps the repository even when nobody has pushed.
 *
 * The file carries an integrity line so a later `init --github` can tell the
 * difference between "our file, possibly from an older template" (safe to update)
 * and "the user edited this" (never silently overwritten).
 */

const INTEGRITY_PREFIX = "# agent-runtime-map-integrity: ";

export const GITHUB_WORKFLOW_RELATIVE_PATH = ".github/workflows/agent-runtime-map.yml";

/**
 * The template deliberately grants nothing beyond `contents: read`, cancels
 * superseded runs per ref, and never commits to the user's branch — the map is an
 * artifact and a step summary, not a push, so no run can trigger another.
 */
export function githubWorkflowTemplate(options: { defaultBranch?: string } = {}): string {
  // A detected default branch narrows push builds to it; without one, every push
  // builds — hardcoding "main" would silently disable master/trunk repositories.
  // JSON.stringify produces a double-quoted scalar YAML accepts verbatim, so a
  // branch name containing a comma or quote cannot break the array syntax.
  const push = options.defaultBranch
    ? `push:\n    branches: [${JSON.stringify(options.defaultBranch)}]`
    : "push:";
  const body = `# Generated by \`agent-runtime-map init --github\`.
# Re-running init updates this file only while it is unmodified; edits are yours to keep.
name: Agent Runtime Map

on:
  ${push}
  pull_request:
  workflow_dispatch:
  schedule:
    # Weekly, so a compatible analyzer update re-maps the repository even
    # without a push. Remove this block if you only want push/PR builds.
    - cron: "17 6 * * 1"

permissions:
  contents: read

concurrency:
  group: agent-runtime-map-\${{ github.ref }}
  cancel-in-progress: true

jobs:
  map:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Full history keeps the previous map's commit reachable, so the change
          # report can name the files that actually changed instead of the event.
          fetch-depth: 0
      - uses: TheCrazyAnt/agent-runtime-map@v1
`;
  return `${INTEGRITY_PREFIX}${integrityOf(body)}\n${body}`;
}

/**
 * The repository's default branch, asked of git rather than assumed. The origin's
 * recorded HEAD is authoritative. Without any origin, a fresh local repository's
 * current branch IS its default. But when an origin exists and its HEAD is not
 * recorded, the current branch proves nothing — someone running init from
 * feat/foo would otherwise pin the workflow to feat/foo and silently disable
 * default-branch pushes — so the answer is undefined and the workflow builds on
 * every push instead of guessing.
 */
export async function detectDefaultBranch(root: string): Promise<string | undefined> {
  const git = async (...args: string[]) => (await execFileAsync("git", ["-C", path.resolve(root), ...args])).stdout.trim();
  try {
    const originHead = await git("symbolic-ref", "refs/remotes/origin/HEAD");
    const name = originHead.replace(/^refs\/remotes\/origin\//, "");
    if (name && name !== originHead) return name;
  } catch {
    // No origin HEAD recorded; whether the local branch means anything depends
    // on whether an origin exists at all.
  }
  try {
    const remotes = (await git("remote")).split("\n").map((line) => line.trim()).filter(Boolean);
    if (remotes.includes("origin")) return undefined;
  } catch {
    return undefined;
  }
  try {
    const branch = await git("symbolic-ref", "--short", "HEAD");
    return branch || undefined;
  } catch {
    return undefined;
  }
}

function integrityOf(body: string): string {
  return createHash("sha256").update(body).digest("hex").slice(0, 16);
}

/**
 * Whether existing workflow content is an unmodified product of this generator —
 * any version of it. The hash covers everything below the integrity line, so a
 * single edited character makes the file the user's.
 */
export function isGeneratedWorkflow(content: string): boolean {
  const newline = content.indexOf("\n");
  if (newline < 0 || !content.startsWith(INTEGRITY_PREFIX)) return false;
  const declared = content.slice(INTEGRITY_PREFIX.length, newline).trim();
  return declared === integrityOf(content.slice(newline + 1));
}

export type GithubWorkflowOutcome = "created" | "updated" | "overwritten" | "unchanged";

export class WorkflowModifiedError extends Error {
  constructor(public readonly workflowFile: string) {
    super(`${workflowFile} exists and has local modifications; it was not touched. Re-run with --force to overwrite it.`);
    this.name = "WorkflowModifiedError";
  }
}

export async function initGithubWorkflow(
  root: string,
  options: { force?: boolean; defaultBranch?: string } = {},
): Promise<{ workflowFile: string; outcome: GithubWorkflowOutcome; defaultBranch?: string }> {
  const workflowFile = path.join(path.resolve(root), GITHUB_WORKFLOW_RELATIVE_PATH);
  const defaultBranch = options.defaultBranch ?? await detectDefaultBranch(root);
  const next = githubWorkflowTemplate({ defaultBranch });

  let existing: string | undefined;
  try {
    existing = await readFile(workflowFile, "utf8");
  } catch {
    existing = undefined;
  }

  if (existing !== undefined) {
    if (existing === next) return { workflowFile, outcome: "unchanged", defaultBranch };
    const generated = isGeneratedWorkflow(existing);
    if (!generated && !options.force) throw new WorkflowModifiedError(workflowFile);
    await writeFile(workflowFile, next, "utf8");
    // "updated" is routine template refresh; "overwritten" says user work was
    // discarded — the caller should word those differently.
    return { workflowFile, outcome: generated ? "updated" : "overwritten", defaultBranch };
  }

  await mkdir(path.dirname(workflowFile), { recursive: true });
  await writeFile(workflowFile, next, "utf8");
  return { workflowFile, outcome: "created", defaultBranch };
}
